on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mutation Testing
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Test with cosmic-ray
        run: |
          cosmic-ray init pyproject.toml cosmic.sqlite
          cosmic-ray --verbosity=INFO baseline pyproject.toml
          cr-filter-git cosmic.sqlite
